# Generated by Django 2.1.7 on 2019-03-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0003_auto_20190304_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_quantity',
            new_name='units_taken',
        ),
    ]
