# Generated by Django 2.1.7 on 2019-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0004_auto_20190320_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shopping_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
