# Generated by Django 2.1.7 on 2019-04-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0007_auto_20190406_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
    ]
