# Generated by Django 2.1.7 on 2019-04-10 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0008_auto_20190410_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationpassword',
            name='current',
        ),
        migrations.RemoveField(
            model_name='validationpassword',
            name='date',
        ),
        migrations.AddField(
            model_name='validationpassword',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationpassword',
            name='digest',
            field=models.CharField(max_length=50),
        ),
    ]
