# Generated by Django 2.1.7 on 2019-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0009_auto_20190410_0459'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
