# Generated by Django 2.1.7 on 2019-04-21 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0010_auto_20190410_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiver_signed',
        ),
        migrations.AddField(
            model_name='order',
            name='waiver',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tallyhq.Waiver'),
            preserve_default=False,
        ),
    ]
