# Generated by Django 2.1.7 on 2019-04-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0012_item_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shopping_date',
            new_name='checkout_time',
        ),
    ]
