# Generated by Django 2.1.7 on 2019-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0013_auto_20190422_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='69 Forbes Ave, Pittsburgh PA', max_length=100),
            preserve_default=False,
        ),
    ]
