# Generated by Django 2.1.7 on 2019-04-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0014_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
