# Generated by Django 2.1.7 on 2019-04-23 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0015_auto_20190422_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('last_name',)},
        ),
    ]
