# Generated by Django 2.1.7 on 2019-04-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0017_auto_20190428_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
