# Generated by Django 2.1.7 on 2019-04-30 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0020_auto_20190428_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('checkout_time',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
