# Generated by Django 2.1.7 on 2019-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0021_auto_20190430_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
