# Generated by Django 2.1.7 on 2019-05-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0022_auto_20190501_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tallyhq.Teacher', unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
    ]
