# Generated by Django 2.1.7 on 2019-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0029_auto_20190501_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password_hash',
            field=models.CharField(default='1234', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('password_hash', 'teacher')},
        ),
    ]
