# Generated by Django 2.1.7 on 2019-05-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0030_auto_20190502_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationpassword',
            name='digest',
            field=models.CharField(max_length=65),
        ),
    ]
