# Generated by Django 2.1.7 on 2019-05-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallyhq', '0031_auto_20190502_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationpassword',
            name='hash_digest',
            field=models.CharField(default='cmu123', max_length=65),
            preserve_default=False,
        ),
    ]
